language: java
jdk:
 - openjdk11
deploy:
  provider: heroku
  api-key:
    secure: J+lOTo/LO2a14Zp35tVDjP3KIakr/PYd8cadrMVP5t5SM8TyO0CaWh1NDjFUbqfkLUox8jI1rIQKaUcjrTj2IeOovM8Ihjg+ZtOYpsy0oMloJRgFhMvNC9SIitzYPxZg3eBXuqbGnQ8cLBS/skL82oHuB3Km4IAeqSCiW6ubxY1lYkF31VegfzUY8ph56++wb0/SYPCubHvpN7W90yO0HT7sVZTqiR9kcvH2Il5G/J9K6z31to5TPKFd6CE+0J+AghqxbIJgqUaWegcrQtMZFqVUOZMeaA9KRUSPnJ0iRCOUx4N3ms/S53kN3Kip57M7jR+XbNOfckACkMfDvToO6elHbTRfOhHqDsEZFOFXTcDT0kLx2u4hKm53IgK1idTWyjYXmiM+MYfIN1O51NsdXcllJVqAfUPh5mVo8hGQI99DxuELEkOsHWUSaE8ROqBYQTMKYIhz1WXB/IkPYADVUryf69e/30xI/wQAE0bJas97cJErRvcALtu2WD5Myegci9kG3nrDTr/ljI5GoDDDWCJ/d0N/R3THLmiY/fwzfa4VMAUbSIvZ1XC3e4icBdsL698jrWNzkY448E0BUH2WFhFZMkiN70KhKq4A7a2/2G8TFRWVAP2HxczGuu4gM/xl78H48blo08HtfRDsJy3qK7FqzBAl24qQKP45nvDVUKE=
  app: gamestore-api
dist: trusty